-- INTENCIONALMENTE VAZIA. O reparo mudou de lugar; a entrada fica.
--
-- Esta migration nasceu para realinhar os dados as' duas regras novas do ciclo
-- de cartao (o dia do fechamento pertence a' fatura seguinte; despesa no credito
-- pesa no mes em que a fatura vence). Ela fazia isso deslocando TODO periodo de
-- fatura em um dia, assumindo que toda linha tinha sido gerada pela convencao
-- antiga.
--
-- A suposicao morreu antes de a migration rodar: o deploy do codigo novo veio
-- primeiro, e o app materializou faturas com a convencao NOVA nesse intervalo.
-- Um deslocamento cego estragaria justamente as que ja' estavam certas. E ele
-- nunca teria consertado o caso que apareceu depois — cartao cujo dia de
-- fechamento foi EDITADO, com faturas descrevendo um ciclo que o cartao nao tem
-- mais.
--
-- O reparo agora e' `resyncCardStatements` (src/db/materialize.ts), chamado pelo
-- script `pnpm db:resync-cards` e pela propria edicao de cartao. Ele deriva o
-- periodo do cartao em vez de deslocar o que esta' gravado: e' idempotente,
-- independe de quando a fatura foi criada e cobre os dois casos.
--
-- O arquivo continua aqui, vazio, porque a entrada correspondente no
-- `_journal.json` ja' foi publicada — remover uma e deixar a outra quebraria o
-- runner em qualquer banco que ja' a tenha registrado.
SELECT 1;
